name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Homework
      run: |
        cd CCGHomework
        mkdir build
        cd build
        cmake ..
        cmake --build .
