name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Homework
      run: |
        cd CCGHomework
        mkdir build
        cd build
        cmake ..
        cmake --build build
